### ISSUE TITLE
Compare river flow at GRDC stations with measured river flow

### ISSUE THREAD

**Issue by coroa** [hydro-python/hydropowerlib#3]
- [x] Request GRDC data for all stations in Germany for as many years as possible
- [ ] Do correlation plots: KDE (KDEpy) and scatterplot or hexbin.
  - [ ] With flows from Geesthacht (depends on #2) @birgits 
  - [ ] With flows from Runoff aggregation (depends on #1) @coroa (using atlite)
  - [ ] With flows from EFAS (see also #9) @coroa

**Comment by coroa** [comment]
Read in measured data from GRDC stations:
```python
from pathlib import Path
import pandas as pd

p = Path("/mnt/rli-server/04_Projekte/163_Open_FRED/03-Projektinhalte/AP2 Wetterdaten/Hydro/bfg_grdc/data")
time_series = pd.concat({int(fn.name.split("_")[0]):
                         pd.read_csv(fn, comment="#", sep=';', index_col=0, usecols=[0,2], na_values=["-999"], parse_dates=True)[' Value']
                         for fn in p.glob("*.txt")}, axis=1)
```
